-- Guías paso a paso para cada tarea y la caminata consciente nueva.
-- Pegar completo en el SQL Editor de Supabase y ejecutar una sola vez.

alter table catalogo_tareas add column if not exists guia text;

update catalogo_tareas set guia = 'Siéntate cómoda, inhala por la nariz contando 4, sostén el aire contando 7 y exhala por la boca contando 8, como apagando una velita. Repite el ciclo unas 8 veces. Si te mareas un poco al inicio es normal, baja los números a 3-5-6.' where id = 1;
update catalogo_tareas set guia = 'Es un ancla para cuando la mente se acelera. Donde estés, di en voz baja o mentalmente 5 cosas que ves, 4 sonidos que oyes y 3 texturas que tocas. Hazlo lento, como describiéndoselo a alguien que no está ahí.' where id = 2;
update catalogo_tareas set guia = 'Acuéstate o siéntate y cierra los ojos. Recorre tu cuerpo despacio desde los pies hasta la cabeza, notando cómo se siente cada parte sin cambiar nada, solo observando. Donde encuentres tensión, respira hacia ahí y suéltala al exhalar.' where id = 3;
update catalogo_tareas set guia = 'Divide una hoja en dos columnas, lo que depende de mí y lo que no. Vacía todas tus preocupaciones y repártelas. Con las de tu columna elige una acción pequeña, y a las otras dales permiso de existir sin cargarlas hoy.' where id = 4;
update catalogo_tareas set guia = 'Lleva la oreja derecha hacia el hombro y sostén 20 segundos, cambia de lado. Luego sube los hombros hacia las orejas, sostén 5 segundos y suéltalos de golpe, tres veces. Termina dibujando círculos lentos con los hombros hacia atrás.' where id = 5;
update catalogo_tareas set guia = 'Antes de dormir escribe tres cosas que salieron bien hoy, por chiquitas que sean, el café estuvo rico también cuenta. El chiste es escribir también por qué salieron bien. Entrena al cerebro a registrar lo bueno, que por diseño se le escapa.' where id = 6;
update catalogo_tareas set guia = 'Elige un momento del día que disfrutaste aunque durara segundos y descríbelo con detalle, dónde estabas, qué se sentía, qué lo hizo bueno. Escribir los detalles alarga el efecto del momento.' where id = 7;
update catalogo_tareas set guia = 'Escríbele unas líneas a la persona que eras hace un año. Cuéntale qué ha pasado, qué superaste que entonces parecía imposible, y qué te gustaría que supiera. No la corrijas, agradécele.' where id = 8;
update catalogo_tareas set guia = 'Pon la canción que te prenda, sube el volumen y muévete sin coreografía y sin espejo, nadie te ve. Una sola canción completa, de principio a fin. El cuerpo suelta lo que la mente lleva cargando.' where id = 9;
update catalogo_tareas set guia = 'Deja el teléfono en casa y sal a caminar 10 minutos sin destino. Fíjate en tres cosas que nunca habías notado de tu calle. Caminar sin estímulos le da espacio a la mente para acomodarse sola.' where id = 10;
update catalogo_tareas set guia = 'Arma una lista con 5 canciones que te bajen las revoluciones, no las más tristes, las que te calman. Guárdala con un nombre que te haga sonreír. Es tu botiquín sonoro para los días difíciles.' where id = 11;
update catalogo_tareas set guia = 'Mándale un mensaje a alguien que quieras sin pedir nada a cambio, solo me acordé de ti, o gracias por la otra vez. Corto y honesto. La conexión se riega con gestos chiquitos y frecuentes.' where id = 12;
update catalogo_tareas set guia = 'Dile a una persona algo concreto que hizo y que te ayudó, entre más específico mejor, gracias por escucharme el martes sin juzgarme. Lo específico se siente verdadero, lo genérico se olvida.' where id = 13;
update catalogo_tareas set guia = 'Elige a esa persona con la que llevas tiempo sin hablar y márcale, aunque sean 10 minutos. Si da nervio, empieza con me acordé de ti y quise saber cómo estás. Casi siempre del otro lado también querían llamar.' where id = 14;
update catalogo_tareas set guia = 'Hoy a las 8 asómate al círculo, aunque solo leas lo que otras personas comparten. Escuchar también es participar, y conocer historias parecidas a la tuya baja la sensación de estar sola en esto.' where id = 15;
update catalogo_tareas set guia = 'Piensa en esa conversación pendiente y escríbela primero, qué necesitas decir, qué sientes, qué pedirías. No la mandes todavía. Escribirla ordena, y ya ordenada decides si la dices, cuándo y cómo.' where id = 16;
update catalogo_tareas set guia = 'Recuerda una discusión reciente y escribe qué sentías debajo del enojo, casi siempre hay miedo, tristeza o cansancio disfrazados. Nombrar la emoción de abajo cambia la próxima conversación.' where id = 17;
update catalogo_tareas set guia = 'Haz dos listas de tu día, qué me dio energía y qué me la quitó. Sin juzgar, solo registra. Después de unos días vas a ver patrones claros, y ahí es donde empiezan las buenas decisiones.' where id = 18;
update catalogo_tareas set guia = 'Escribe tres cosas que te importan de verdad, honestidad, familia, crear, lo que sea. Junto a cada una anota un momento de hoy en que actuaste conforme a ella, o en que te alejaste. Conocer tus valores es tener brújula.' where id = 19;
update catalogo_tareas set guia = 'Toma papel y algo para dibujar y dale forma a lo que sientes, colores, rayones, formas abstractas, no importa que no quede bonito. No lo pienses, deja que la mano hable. Al final ponle un título.' where id = 20;
update catalogo_tareas set guia = 'Abre el panel de lecturas y elige la que te llame, son de 3 a 5 minutos. Léela despacio y quédate con una sola idea, la que más te haya movido. Una idea aplicada vale más que diez leídas.' where id = 21;
update catalogo_tareas set guia = 'Media hora antes de dormir deja el teléfono cargando fuera de tu cuarto, o lo más lejos de la cama que puedas. Si lo usas de alarma, hoy es buen día para conseguir un despertador. Las primeras noches cuesta, después se agradece.' where id = 22;
update catalogo_tareas set guia = 'Dedícale 10 minutos a tu cuarto pensando en dormir mejor, baja la luz, ventila tantito, acomoda la cama, aleja los pendientes visibles. Tu cuarto le manda señales a tu cerebro, procura que digan descanso.' where id = 23;
update catalogo_tareas set guia = 'Prepárate un té o agua caliente y tómatelo sin ninguna pantalla enfrente, solo tú y la taza, sintiendo el calor y el sabor. Cinco minutos de no hacer nada también son una forma de cuidarte.' where id = 24;

insert into catalogo_tareas (titulo, objetivo, categoria, dificultad, minutos, guia)
select 'Camina 30 minutos al aire libre, mirando tu entorno', 'animo', 'movimiento', 2, 30, 'Sal a un parque o donde haya pasto y camina sin audífonos, a paso cómodo. Cuando la mente se vaya a los pendientes, regrésala con suavidad a lo que ves, los árboles, la luz, la gente, los sonidos. No intentes dejar la mente en blanco a la fuerza, solo vuelve a mirar, una y otra vez. Eso es meditar caminando.'
where not exists (select 1 from catalogo_tareas where titulo = 'Camina 30 minutos al aire libre, mirando tu entorno');
